import React, { useState, useEffect } from 'react';
import { getDashboardSummary } from '../services/api';
import { Layers, CheckCircle2, AlertTriangle, Shield, Database, Zap, HardDrive, BarChart3 } from 'lucide-react';
import PageHeader from '../components/ui/PageHeader';

// Animated stat block with icon
const StatBlock = ({ label, value, color = 'slate', icon: Icon }) => {
  const colorMap = {
    slate:   { text: 'text-slate-900 dark:text-white',         bg: 'bg-slate-100 dark:bg-white/5',           icon: 'text-slate-400 dark:text-slate-500' },
    sky:     { text: 'text-sky-600 dark:text-sky-400',          bg: 'bg-sky-50 dark:bg-sky-500/10',           icon: 'text-sky-500 dark:text-sky-400' },
    indigo:  { text: 'text-indigo-600 dark:text-indigo-400',    bg: 'bg-indigo-50 dark:bg-indigo-500/10',     icon: 'text-indigo-500 dark:text-indigo-400' },
    amber:   { text: 'text-amber-600 dark:text-amber-400',      bg: 'bg-amber-50 dark:bg-amber-500/10',       icon: 'text-amber-500 dark:text-amber-400' },
    rose:    { text: 'text-rose-600 dark:text-rose-400',        bg: 'bg-rose-50 dark:bg-rose-500/10',         icon: 'text-rose-500 dark:text-rose-400' },
    emerald: { text: 'text-emerald-600 dark:text-emerald-400',  bg: 'bg-emerald-50 dark:bg-emerald-500/10',   icon: 'text-emerald-500 dark:text-emerald-400' },
  };

  const c = colorMap[color] || colorMap.slate;

  return (
    <div className={`p-4 ${c.bg} rounded-2xl border border-slate-100 dark:border-white/5 space-y-2 group hover:scale-[1.02] transition-transform duration-200`}>
      <div className="flex items-center gap-2">
        {Icon && <Icon className={`w-4 h-4 ${c.icon}`} />}
        <span className="text-[11px] text-slate-400 dark:text-slate-500 uppercase font-bold tracking-wider">{label}</span>
      </div>
      <div className={`text-2xl font-extrabold tracking-tight ${c.text}`}>{value ?? '—'}</div>
    </div>
  );
};

// Highlight card for architecture notes
const ArchitectureNote = ({ icon: Icon, text, color = 'emerald' }) => {
  const colorMap = {
    emerald: 'text-emerald-500 bg-emerald-500/10',
    sky:     'text-sky-500 bg-sky-500/10',
    indigo:  'text-indigo-500 bg-indigo-500/10',
    amber:   'text-amber-500 bg-amber-500/10',
  };
  return (
    <div className="flex items-start gap-3 p-4 rounded-xl bg-slate-50 dark:bg-white/[0.03] border border-slate-100 dark:border-white/5 hover:border-slate-200 dark:hover:border-white/10 transition-colors group">
      <span className={`flex-shrink-0 mt-0.5 w-6 h-6 rounded-lg flex items-center justify-center ${colorMap[color]}`}>
        {Icon ? <Icon className="w-3.5 h-3.5" /> : <CheckCircle2 className="w-3.5 h-3.5" />}
      </span>
      <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">{text}</p>
    </div>
  );
};

// Skeleton
const WorkflowSummarySkeleton = () => (
  <div className="p-6 space-y-6 max-w-5xl animate-pulse">
    <div className="h-8 w-72 bg-slate-200 dark:bg-white/10 rounded-xl" />
    <div className="glass-panel p-6 space-y-6">
      <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-slate-800">
        <div className="space-y-2">
          <div className="h-5 w-48 bg-slate-200 dark:bg-white/10 rounded" />
          <div className="h-3 w-36 bg-slate-100 dark:bg-white/5 rounded" />
        </div>
        <div className="h-6 w-32 bg-slate-100 dark:bg-white/5 rounded-full" />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {[...Array(6)].map((_, i) => (
          <div key={i} className="p-4 bg-slate-100 dark:bg-white/5 rounded-2xl space-y-2">
            <div className="h-2.5 w-28 bg-slate-200 dark:bg-white/10 rounded" />
            <div className="h-7 w-20 bg-slate-200 dark:bg-white/10 rounded" />
          </div>
        ))}
      </div>
    </div>
  </div>
);

const WorkflowSummary = () => {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getDashboardSummary()
      .then((res) => {
        setSummary(res.data);
        setLoading(false);
      })
      .catch((err) => {
        console.error(err);
        setLoading(false);
      });
  }, []);

  if (loading) return <WorkflowSummarySkeleton />;
  if (!summary) return null;

  const successRate = summary.processing_success_rate ?? 100;

  return (
    <div className="p-6 space-y-6 max-w-5xl animate-fade-up">
      <PageHeader
        title="Executive Workflow Report"
        subtitle="Consolidated execution metrics and efficiency report generated by the Excel Engine pipeline."
      />

      {/* System Health Banner */}
      <div className="glass-panel p-5 flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
            <CheckCircle2 className="w-5 h-5 text-emerald-500" />
          </div>
          <div>
            <div className="font-bold text-slate-900 dark:text-white tracking-tight">System Status: Healthy</div>
            <div className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">All pipeline components operating normally</div>
          </div>
        </div>
        <div className="flex items-center gap-4 text-sm">
          <div className="text-center">
            <div className="text-xl font-extrabold text-emerald-600 dark:text-emerald-400">{successRate}%</div>
            <div className="text-[11px] text-slate-500 dark:text-slate-400 font-semibold">Success Rate</div>
          </div>
          <div className="w-px h-10 bg-slate-200 dark:bg-white/10" />
          <div className="text-center">
            <div className="text-xl font-extrabold text-sky-600 dark:text-sky-400">{summary.total_batches ?? 0}</div>
            <div className="text-[11px] text-slate-500 dark:text-slate-400 font-semibold">Batches Run</div>
          </div>
          <div className="w-px h-10 bg-slate-200 dark:bg-white/10" />
          <div className="text-center">
            <div className="text-xl font-extrabold text-rose-500 dark:text-rose-400">{summary.failed_files ?? 0}</div>
            <div className="text-[11px] text-slate-500 dark:text-slate-400 font-semibold">Failed Files</div>
          </div>
        </div>
      </div>

      {/* Core Metrics Grid */}
      <div className="glass-panel p-5 space-y-4">
        <div className="flex items-center gap-2 pb-3 border-b border-slate-200 dark:border-white/5">
          <BarChart3 className="w-4 h-4 text-sky-500" />
          <h2 className="font-bold text-slate-900 dark:text-white tracking-tight">Core Pipeline Metrics</h2>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <StatBlock icon={HardDrive}    label="Total Scanned Files"     value={summary.total_files?.toLocaleString()}   color="slate"   />
          <StatBlock icon={Database}     label="Consolidated Records"    value={summary.total_records?.toLocaleString()}  color="sky"     />
          <StatBlock icon={Layers}       label="Batches Executed"        value={summary.total_batches}                    color="indigo"  />
          <StatBlock icon={AlertTriangle}label="Duplicate Count"         value={summary.total_duplicates}                 color="amber"   />
          <StatBlock icon={Zap}          label="Failed Files"            value={summary.failed_files}                     color="rose"    />
          <StatBlock icon={CheckCircle2} label="Processing Success Rate" value={`${successRate}%`}                        color="emerald" />
        </div>
      </div>

      {/* Architecture Highlights */}
      <div className="glass-panel p-5 space-y-4">
        <div className="flex items-center gap-2 pb-3 border-b border-slate-200 dark:border-white/5">
          <Shield className="w-4 h-4 text-indigo-500" />
          <h2 className="font-bold text-slate-900 dark:text-white tracking-tight">Key Architecture Highlights</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <ArchitectureNote
            icon={Zap}
            color="emerald"
            text="Consumes raw outputs cleanly from background Excel batches without modifying core worker code."
          />
          <ArchitectureNote
            icon={Database}
            color="sky"
            text="FTS5 and indexed SQLite backend handle instant full-text queries for 100,000+ extracted rows."
          />
          <ArchitectureNote
            icon={Shield}
            color="indigo"
            text="Duplicate detection flags duplicate hashes and filenames for safe review — nothing is auto-deleted."
          />
          <ArchitectureNote
            icon={Layers}
            color="amber"
            text="Role-based stealth authentication supports Admin, CEO, Marketing, and Developer access levels."
          />
        </div>
      </div>
    </div>
  );
};

export default WorkflowSummary;
